version: "3.7"

services:
  # SIMPLE TRAEFIK DASH #
  simple-traefik-dash:
    image: msjpq/simple-traefik-dash
    labels:
      - traefik.http.services.std.loadbalancer.server.port=5050
      - traefik.http.routers.std.tls.options=default
      - traefik.http.routers.std.rule=Host("<Something>")
    environment:
      - STD_TRAEFIK_API=http://traefik:8080/ # Required, make sure you can actually talk to Traefik
      - STD_TRAEFIK_ENTRY_POINTS=web-secure # Required, only routes using entrypoints will be parsed
      - STD_TRAEFIK_EXIT_PORT=443 # Required, your exit port
      - STD_TITLE=🐳 # Optional, page title
    volumes:
      - ./more.csv:/std/more-routes/more.csv # Optional - CSV Columns: name, uri
      - ./ignore.csv:/std/ignore-routes/ignore.csv # Optional - CSV Column: name
      - ./views/:/std/views/ # Optional - If you want to override CSS & JS
networks:
  default:
    external: true
    name: traefik-reverse-proxy
